### ISSUE TITLE
mono, 32bit float MP3s play uncontrollably fast in AntennaPod

### ISSUE THREAD

**Issue by Cathryne** [TheRealFalcon/Prestissimo#20]
On a [FairphoneOS 1.1](http://buy-a-phone-start-a-movement.fairphone.com/en/specs/) in [AntennaPod](https://github.com/danieloeh/AntennaPod) v[0.9.8.2](https://github.com/danieloeh/AntennaPod/releases/tag/0.9.8.2) by @danieloeh using [Prestissimo 0.5](https://f-droid.org/repository/browse/?fdid=com.falconware.prestissimo), MP3 files are always played at very high/maximum speed & with high pitch, if they are encoded in mono, 32bit float. No matter which speed is actually set. Stereo 32bit float MP3s play fine.

I'm not sure in which of the above 3 components this error is located, sorry.

Edit: Previously, I thought .ogg files were the problem. Corrected by checking a hand-full of chipmunk-sounding files in Audacity against normally sounding ones.

**Comment by Ph1b** [comment]
Is there any news on this?
We are having the exact same problems over here:
https://github.com/Ph1b/MaterialAudiobookPlayer/issues/129
https://github.com/Ph1b/MaterialAudiobookPlayer/issues/53
